name: Super-Linter


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checkout ditt repository
      - name: Checkout repository
        uses: actions/checkout@v2

     
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT: false
          VALIDATE_PYTHON: false
          VALIDATE_PHP: false
          VALIDATE_HTML: false
          VALIDATE_CSS: false
