name: Super-Linter

# Kontrollerar när lintern ska köras
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Definierar jobbet för att köra Super-Linter
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      # Checkout ditt repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Kör Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          VALIDATE_JAVASCRIPT: false
          VALIDATE_PYTHON: false
          VALIDATE_PHP: false
          VALIDATE_HTML: false
          VALIDATE_CSS: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
